- name: Install Python and MySQL client
  apt:
    name:
      - python3
      - python3-pip
      - default-libmysqlclient-dev
      - python3-dev
      - python3-venv 
    state: present
    update_cache: yes
  become: true

- name: Create requirements.txt
  copy:
    dest: /home/ubuntu/requirements.txt
    content: |
      flask
      flask-mysqldb

- name: Create a virtual environment (using python3 -m venv)
  command: python3 -m venv /home/ubuntu/venv
  args:
    creates: /home/ubuntu/venv
  become: false

- name: Install Python packages in venv using pip
  command: /home/ubuntu/venv/bin/pip install flask flask-mysqldb
  become: false


- name: Copy Flask app
  copy:
    dest: /home/ubuntu/app.py
    content: |
      from flask import Flask
      from flask_mysqldb import MySQL

      app = Flask(__name__)

      app.config['MYSQL_HOST'] = '{{ hostvars["database"].ansible_host }}'

      app.config['MYSQL_USER'] = 'ansibleadmin'
      app.config['MYSQL_PASSWORD'] = 'secretpass'
      app.config['MYSQL_DB'] = 'sampledb'

      mysql = MySQL(app)

      @app.route("/")
      def hello():
          cur = mysql.connection.cursor()
          cur.execute("SELECT text FROM messages LIMIT 1;")
          message = cur.fetchone()
          cur.close()
          return message[0] if message else "No message found"
      if __name__ == "__main__":
          app.run(host="0.0.0.0", port=5000)

- name: Start Flask app
  shell: |
    source /home/ubuntu/venv/bin/activate
    FLASK_APP=/home/ubuntu/app.py nohup flask run --host=0.0.0.0 --port=5000 &
  args:
    executable: /bin/bash
  async: 30
  poll: 0

